steps:
  - name: node:10.15.1
    entrypoint: yarn
    args: ["install"]
    dir: "cloud_functions/functions"
  - name: node:10.15.1
    entrypoint: yarn
    args:
      - "deploy"
      - "--project"
      - "${_PROJECT_ID}"
      - "--token"
      - "${_FIREBASE_TOKEN}"
      - "--only"
      - "functions:${_FUNCTIONS_GROUP}"
    dir: "cloud_functions/functions"

substitutions:
  _PROJECT_ID: "project-id" # default value
  _FUNCTIONS_GROUP: "exportTable" # default value
