steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      - kms
      - decrypt
      - --ciphertext-file=www/.env.enc
      - --plaintext-file=www/.env
      - --location=global
      - --keyring=antler-vc
      - --key=cloudbuild-env
  - name: node:10.15.1
    entrypoint: yarn
    args: ["install"]
    dir: "www"
  - name: node:10.15.1
    entrypoint: yarn
    args: ["build"]
    dir: "www"
  - name: node:10.15.1
    entrypoint: yarn
    args: ["deploy"]
    dir: "www"
