[build]
  base = "www/"
  command = "yarn build"
  publish = "build/"

[template.environment]
  REACT_APP_FIREBASE_PROJECT_ID = "you firebase project Id"
  REACT_APP_FIREBASE_PROJECT_WEB_API_KEY = "your firebase web api key"
  REACT_APP_ALGOLIA_APP_ID = "optional algolia app id"
  REACT_APP_ALGOLIA_SEARCH_API_KEY = "optional algolia search api key"